### ISSUE TITLE
引入 IView 组件库报错

### ISSUE THREAD

**Issue by zhangminggeek** [FEMessage/vue-sfc-cli#111]
## Describe the bug
在 styleguide.config.js 中引入组件库 IView 时报错

## Screenshots
```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'require'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           require: …
         }
       })
     ]
```

## To Reproduce
1. 创建 styleguide/iview.js 文件
2. 引入组件库
```javascript
import Vue from 'vue';
import ViewUI from 'view-design';
import 'view-design/dist/styles/iview.css';

Vue.use(ViewUI);
```
3. 在 styleguide.cofig.js 中引入
```javascript
module.export = {
// ...
require: ['./styleguide/iview.js'],
}
```
4. 提示错误 `configuration has an unknown property 'require'. `

## Expected behavior
```
These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
```

## environment information
 - Version [1.11.2]
 - OS: [Mac OS]
 - Browser [chrome]

**Comment by levy9527** [comment]
抱歉，久等了，我们安排debug下。

**Comment by donaldshen** [comment]
### 结论
未能重现。

### 步骤
1. npx vue-sfc-cli
生成项目 temp

2. 执行 yarn && yarn dev，正常

3. 新增 styleguide/iview.js，在 styleguide.config.js 中引入
![image](https://user-images.githubusercontent.com/19591950/82640979-2754dd80-9c3e-11ea-9f6b-b426f3e19f68.png)

4. 在 src/temp.vue 新增按钮
![image](https://user-images.githubusercontent.com/19591950/82641026-405d8e80-9c3e-11ea-89a2-f1a5b346cdd4.png)

5. yarn dev，报错，发现是图中代码引入了 svg 未被处理
![image](https://user-images.githubusercontent.com/19591950/82641076-5408f500-9c3e-11ea-8e91-26a3368c78ee.png)

6. yarn add -D raw-loader，添加到 styleguide.config.js
![image](https://user-images.githubusercontent.com/19591950/82641195-89adde00-9c3e-11ea-9740-cf127a69844e.png)

7. 结果正常
![image](https://user-images.githubusercontent.com/19591950/82641183-8581c080-9c3e-11ea-8a41-622f53f594a9.png)

### 推测
根据你的 screenshots 所描述，应该是把 require 行放入了 webpackConfig 属性下。调整了位置，报错
![image](https://user-images.githubusercontent.com/19591950/82641335-c679d500-9c3e-11ea-834e-00860e74f89f.png)

![image](https://user-images.githubusercontent.com/19591950/82641268-ad712400-9c3e-11ea-80ea-02310a284406.png)
