### ISSUE TITLE
希望可以实现多组件

### ISSUE THREAD

**Issue by yokiijay** [FEMessage/vue-sfc-cli#112]

**Comment by levy9527** [comment]
sfc 的意思就是 single file component，目的就是为可独立发包的组件提供一个开箱即用的开发环境。
如果是多组件的开发环境，可在社区另寻方案。

**Comment by Skura23** [comment]
> sfc 的意思就是 single file component，目的就是为可独立发包的组件提供一个开箱即用的开发环境。 如果是多组件的开发环境，可在社区另寻方案。

有什么多组件(组件库)开发脚手架推荐么
