### ISSUE TITLE
feature request for upgrade cli in project

### ISSUE THREAD

**Issue by lianghx-319** [FEMessage/vue-sfc-cli#28]
Now, when I want to upgrade my old project to the new cli. The only way is copy. Should the cli provide a command line like --upgrade that transfering file automatically.

**Comment by levy9527** [comment]
相关命令参数如下：-u --upgrade

**Comment by levy9527** [comment]
已实现 https://github.com/FEMessage/vue-sfc-cli/releases/tag/v1.7.0
