### ISSUE TITLE
使用参数代替询问输入

### ISSUE THREAD

**Issue by 2nthony** [FEMessage/vue-sfc-cli#37]
**Is your feature request related to a problem? Please describe.**

否

**Describe the solution you'd like**

像大部分cli工具那样, 接收`process.argv`参数来代替询问输入

**Additional context**

`npx vue-sfc-cli @[ownerName]/[componentName]`, 随后不再询问组件名称, 直接生成模板

如果没有参数， 则询问输入

**Comment by 2nthony** [comment]
候选名单

- commander.js

**Comment by levy9527** [comment]
此功能属于锦上添花，非雪中送碳，暂不考虑。

**Comment by levy9527** [comment]
使用 shell 脚本时，有此需求！

**Comment by eviIIt** [comment]
https://github.com/FEMessage/vue-sfc-cli/blob/dev/init.js#L19
