### ISSUE TITLE
shell script lost execution permission on Windows

### ISSUE THREAD

**Issue by lianghx-319** [FEMessage/vue-sfc-cli#38]
**Describe the bug**
if init component in window system, the shell will permission denied
`
fs.chmodSync(path.join(outDir, 'build.sh'), '755')
fs.chmodSync(path.join(outDir, 'notify.sh'), '755')
`
**Expected behavior**
platform compatibility

**environment information: **
 - Version [1.6.0]
 - OS: [window]

**Comment by levy9527** [comment]
推荐在非windows环境初始化组件
