### ISSUE TITLE
文档中Components目录下出现内部使用的组件定义

### ISSUE THREAD

**Issue by donaldshen** [FEMessage/vue-sfc-cli#40]
**Describe the bug**
文档中出现内部使用的组件定义

**Screenshots**
![image](https://user-images.githubusercontent.com/19591950/57841017-60bd6680-77fc-11e9-952c-33cbeae9fde4.png)

**To Reproduce**
https://femessage.github.io/el-data-table/

**Expected behavior**
文档中只出现导出的组件。建议修改styleguide.config.js模板

**Comment by levy9527** [comment]
@evillt 响应下。

**Comment by 2nthony** [comment]
~~讨论过,也赞同~~

有歧义

例如上面的 `el-loading-button.vue` 作为组件应该放在 `components/` 文件夹内

**Comment by levy9527** [comment]
可在具体开发时由由开发者解决，如把内部模块放到 `components/` 文件夹内
